# Generated by Django 3.2.6 on 2021-09-20 11:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], help_text='Choose the Product type. Is it for free? or paid?', max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set the price to 0 if the product type is free.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('category', models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D')], max_length=20, null=True)),
                ('paidproduct', models.ImageField(blank=True, help_text='Provide a WatermarkProduct.This product is just a showcase to Customers. Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/paid/Characters/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('freeproduct', models.ImageField(blank=True, help_text='Provide a Watermark free Product to distribute to Customers .Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/free/Landscapes/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Landscapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], help_text='Choose the Product type. Is it for free? or paid?', max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('category', models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set the price to 0 if the product type is free.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paidproduct', models.ImageField(blank=True, help_text='Provide a WatermarkProduct.This product is just a showcase to Customers. Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/paid/Landscapes/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('freeproduct', models.ImageField(blank=True, help_text='Provide a Watermark free Product to distribute to Customers .Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/free/Landscapes/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OpticalLens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], help_text='Choose the Product type. Is it for free? or paid?', max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set the price to 0 if the product type is free.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('category', models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D')], max_length=20, null=True)),
                ('paidproduct', models.ImageField(blank=True, help_text='Provide a WatermarkProduct.This product is just a showcase to Customers. Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/paid/OpticalLense/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('freeproduct', models.ImageField(blank=True, help_text='Provide a Watermark free Product to distribute to Customers .Only .png and .jpg are accepted', null=True, upload_to='GraphicsElements/free/OpticalLense/%y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOpticalLense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.purchasedproducts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EHub.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GraphicsElements.opticallens')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLandscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.purchasedproducts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EHub.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GraphicsElements.landscapes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.purchasedproducts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EHub.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GraphicsElements.characters')),
            ],
        ),
    ]
