# Generated by Django 3.2.6 on 2021-09-20 11:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set the price to 0 if the product type is free.', max_digits=6, max_length=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paidproduct', models.FileField(help_text='Provide a DemoVideo. This product is just a showcase to Customers. Only .mp4 and .mov are accepted', null=True, upload_to='OTHERS/AudioSpectrum/paid/%y', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov'])])),
                ('freeproduct', models.FileField(help_text='Provide a file to distribute to Customers .Only .zip and .rar are accepted', null=True, upload_to='OTHERS/AudioSpectrum/free/%y', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LyricsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set the price to 0 if the product type is free.', max_digits=6, max_length=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paidproduct', models.FileField(help_text='Provide a DemoVideo.This product is just a showcase to Customers. Only .mp4 and .mov are accepted.', null=True, upload_to='OTHERS/Lightining/paid/%y', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov'])])),
                ('freeproduct', models.FileField(help_text='Provide a file to distribute to Customers .Only .zip and .rar are accepted', null=True, upload_to='OTHERS/Lightining/free/%y', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLyricsTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.purchasedproducts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EHub.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTHERS.lyricstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAudioSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.purchasedproducts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EHub.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTHERS.audiospectrum')),
            ],
        ),
    ]
